### PR TITLE
UserClaimsFactory to be public

### PR DESCRIPTION
**Pull request by domisginger**
Wanting to create custom IUserClaimsPrincipalFactory overriding IdentityServer's default. Cant override if internal.

My requirements for custom IUserClaimsPrincipalFactory is to change ClaimValueType's which are all being returned as string to the value set in the claims database.

Apologies if I have missed any config that removes this need in the first place.

### CODE REVIEW

**Comment by brockallen** [comment]
Why `public` on the `Decorator`?

**Comment by domisginger** [comment]
Decorator is used in constructor, have to change or

**Comment by brockallen** [comment]
ah ok, I see. ok, so let me think about this. i'm not thrilled about exposing our decorator/DI plumbing. maybe there's a better way to achieve this...

**Comment by domisginger** [comment]
Brilliant thanks for you help. Was able to register my own and then have UserClaimsFactory on top, just had to remember to move the registering above the AddAspNetIdentity call.

Closing.

**Pull request closed without merging**
