### PR TITLE
UserClaimsFactory now adds role claims if supported.

### PR DESCRIPTION
**Pull request by ajtowf**

### CODE REVIEW

**Comment by AndyBursh** [comment]
+1 Would love to see this incorporated. Exactly what I've been looking for.

**Comment by brockallen** [comment]
Why is this needed? The base class will add from the roles, no?

**Comment by ajtowf** [comment]
@brockallen I didn't get the roles without it even though my user had roles, after this change, I got them.

**Comment by brockallen** [comment]
This line of code is doing the same thing: https://github.com/aspnet/Identity/blob/release/src/Microsoft.AspNetCore.Identity/UserClaimsPrincipalFactory.cs#L96

> I didn't get the roles without it even though my user had roles, after this change, I got them.

Can you debug into the base class to investigate further?

**Comment by ajtowf** [comment]
@brockallen sure thing, I'll look into it!

**Comment by brockallen** [comment]
any update?

**Comment by ajtowf** [comment]
I'm going to try to investigate this further tonight, been super busy. I've built an admin UI for managing clients among other things :D Maybe something others would be interested in? Currently specific for EntityFramework.

image

**Comment by ajtowf** [comment]
Right so I've just looked into this. It looks like the roles are added, I've must've done something else wrong. BUT, check this out, this is the claims my identityserver issues, using my own UserClaimsFactory. Pretty much looks the same when using the one from this repo, the important thing is that the role claim type (key) is "role" and not "http://schemas.microsoft.com/ws/2008/06/identity/claims/role"

image

Looks good, right? BUT when debugging the claims from the RP, an MVC app, this is what I get:

image

Who's adding the roles again as the wrong type? Now I have both roles with different keys. Could this perhaps explain the following bug I've issued https://github.com/aspnet/Security/issues/1018 ?

**Comment by ajtowf** [comment]
This is very strange, because when debugging from the "account" page within my identityserver the claims look right: Who's adding the roleclaimtype "http://schemas.microsoft.com/ws/2008/06/identity/claims/role" that I get from the mvc client? 

image

Also, the AuthroizeAttribute still only seems to work if I'm in at least two roles.

**Comment by ajtowf** [comment]
Oh my god, just added the following line to the MVC app and everything looked fine and worked as expected after that.

    JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();

image

Sorry for wasting your time!

**Pull request closed without merging**
