### PR TITLE
Net Core 2.0 and Asp.Net Core 2.0 support

### PR DESCRIPTION
**Pull request by Arkatufus**

### CODE REVIEW

**Comment by Scott-McFadden** [comment]
There is a slight problem in the Index.chtml in the Host project.  The line  "var props = (await Context.HttpContext.ChallengeAsync(authScheme)).Properties;" is throwing an exception.    I don't understand enough about the project to correct this myself.     The system is generating the tokens I need so the core project appears to be sound. 

But for what it is worth, this update was important to me and I need to say thanks for the update!

**Comment by Arkatufus** [comment]
I'll go and check it out, thanks for the heads up

**Comment by terraferma-zz** [comment]
I think Context.Authentication.GetAuthenticateInfoAsync needs to be Context.AuthenticateAsync in Index.cshtml.  I don't see Scott's issue.

**Comment by Scott-McFadden** [comment]
I make have change the call in my original email to ChallengeAsync(authScheme)).Properties; after some research on the .web site.  Sorry for the confusion there.   
However, it boils down to the fact that I needed to comment that section out to get the example site to work properly under the changes pushed out by core 2.0.  
As a side note, the changes that the .net community is experiencing are making it hard to make a stable environment.  All to often changes are make in the "next" release that cause us (the developer community) to fix a lot of things because the middleware tends to simple invalidate functions and features in the prior version(s).  I understand you (the IdentityServer4 folks) are experiencing this as well with the changes to core 2.0, so you must feel my pain here.    Look at this particular change, someone has decided to make a simple change to the way we acquire information by removing the "get" and if forces many downstream changes.  Whereas, the method could have been depreciated rather than replaced outright. 
However, what is more important than the coding challenges this provides is what my management sees.  Now, if we update the nuget library to get the latest code, I need to explain why it is going to take many more hours than expected to fix and test things that were broken because we upgraded to stay current.  This starts to make the stability of .NET look bad.  IMHO, the industry needs to consider this more carefully.
Sorry for the rant, but it is our reality.
Thanks for your attention.
Scott

From: terraferma-zz <notifications@github.com>To: IdentityServer/IdentityServer4.AspNetIdentity <IdentityServer4.AspNetIdentity@noreply.github.com>Cc: Scott-McFadden <improvingcomputers@yahoo.com>; Comment <comment@noreply.github.com>Sent: Friday, September 1, 2017, 12:24:50 PM CDTSubject: Re: [IdentityServer/IdentityServer4.AspNetIdentity] Net Core 2.0 and Asp.Net Core 2.0 support (#34)

I think Context.Authentication.GetAuthenticateInfoAsync needs to be Context.AuthenticateAsync in Index.cshtml. I don't see Scott's issue.

**Comment by brockallen** [comment]
FWIW, I'll have a preview out later today or tomorrow.

**Comment by brockallen** [comment]
Closing since we have an RC out. Thanks.

**Pull request closed without merging**
