### PR TITLE
initial 2fa code

### PR DESCRIPTION
**Pull request by TomCJones**
I am putting this out there as a candidate for dev.
I did need to change a few things in the existing directories, but that should not impact their
 usefulness without enabling 2fa, which is hidden behind a drop down.

### CODE REVIEW

**Comment by TomCJones** [comment]
@brockallen - any feedback now?

**Comment by brockallen** [comment]
Ah, this totally fell of my radar. Sorry. I will have some time near the end of this week.

**Comment by TomCJones** [comment]
there seems to be a problem with this code. Signon works for Edge but not for Chrome. Something about the Context.User returning null.  Could this be the CSP issue?  Do I need to reload something?

**Comment by brockallen** [comment]
I'm flying tomorrow, so I downloaded the branch and will have a look while in the air.

**Comment by TomCJones** [comment]
While looking at it, can you check operation on Chrome. It seems that logins to chrome do not persist. I see you have said that .userauthentication is not necessary for this demo, which seems to be the case for edge, but not chrome. Perhaps there is some other solution. In any case I cannot use this for U2F as it requires https as well. So I need to know if you want a demo UI for U2F or WebAuthN? As https is required, it will need to be a different solution.

**Comment by TomCJones** [comment]
Let me know when you have specific guidance. I will say it took me four times longer to make it work in your models versus theirs. Theirs is running on

**Comment by TomCJones** [comment]
http://idesg-idp.azurewebsites.net

**Comment by leastprivilege** [comment]
I went to your website. What is this idef? And why would I care?

**Comment by TomCJones** [comment]
Good question, I just went to the site and realized that some of the critical links are not shown on the phone version. I will correct that and continue to try to improve the content over time. The site is really new and evolving.  If you want more insight before I fix the site for phone, use a laptop to look at it.

**Comment by brockallen** [comment]
I do appreciate this PR, but given the multitude of UI for identity (ravor vs mvc and more coming), I think I need to close this. I think we've decided that it's not IdentityServer's job to mandate the identity UI and workflow(s), and it's not something I think we have the bandwidth to maintain. This would be a great sample for someone to host on their own repo. Thanks.

**Comment by damienbod** [comment]
If your interested, this is an IdentityServer4 Identity sample with bootstrap 4 and the latest Identity UI bits in MVC form

https://github.com/damienbod/IdentityServer4AspNetCoreIdentityTemplate

**Pull request closed without merging**
